#logging:
#  pattern:
#    level: "%5p %X{mdcLogging}"

#logging:
#  pattern:
#    console: "%d %-5level [%thread] %logger{0} : %msg %X{mdcLogging}%n"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %X{mdcLogging}%n%wEx"


